#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * file is generated from aptex.md using https://github.com/zeitlinger/keyboard/blob/main/generateKeyboard.kt
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(KC_SLASH, KC_C, KC_M, KC_F, KC_Q, KC_Z, KC_Y, KC_O, KC_U, KC_MINUS, KC_R, KC_S, KC_T, KC_H, KC_V, KC_B, KC_N, KC_A, KC_I, KC_L, KC_X, KC_W, KC_G, KC_D, KC_K, KC_J, KC_P, KC_QUOTE, KC_COMMA, KC_DOT, KC_SPC, MO(1), LT(2,KC_BSPC), KC_E),
	[1] = LAYOUT_split_3x5_2(KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, LT(5,KC_R), LALT_T(KC_S), LCTL_T(KC_T), LT(1,KC_H), KC_TRNS, KC_TRNS, LT(1,KC_N), RCTL_T(KC_A), LALT_T(KC_I), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, KC_TRNS),
	[2] = LAYOUT_split_3x5_2(KC_8, KC_7, KC_6, KC_5, KC_NO, KC_PSCR, KC_HOME, KC_PGUP, KC_PGDN, KC_END, KC_4, LALT_T(KC_3), LCTL_T(KC_2), LSFT_T(KC_1), KC_PERC, KC_ESC, RSFT_T(KC_LEFT), RCTL_T(KC_UP), LALT_T(KC_DOWN), KC_RIGHT, KC_CIRC, KC_AT, KC_HASH, KC_9, KC_NO, KC_NO, KC_ENT, KC_INS, KC_DEL, KC_LGUI, KC_0, KC_TAB, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO),
	[4] = LAYOUT_split_3x5_2(KC_F8, KC_F7, KC_F6, KC_F5, KC_NO, RALT(KC_Q), KC_EXLM, KC_LPRN, KC_RPRN, KC_ASTR, KC_F4, LALT_T(KC_F3), LCTL_T(KC_F2), LSFT_T(KC_F1), RALT(KC_S), RALT(KC_P), RSFT_T(KC_SEMICOLON), RCTL_T(KC_LEFT_BRACKET), LALT_T(KC_RIGHT_BRACKET), KC_BACKSLASH, KC_F12, KC_F11, KC_F10, KC_F9, KC_NO, RALT(KC_Y), KC_EQUAL, KC_TILD, KC_DLR, KC_AMPR, KC_SPC, KC_NO, KC_TRNS, KC_TRNS),
	[5] = LAYOUT_split_3x5_2(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_SPC, KC_NO, KC_NO, KC_NO),
};
